default_language_version:
  python: python3.11
repos:
  - repo: local
    hooks:
      - id: pre-commit
        name: run pre-commit.sh script
        entry: hooks/pre-commit.sh
        language: script
        stages: [commit]
        pass_filenames: false
      - id: commit-msg
        name: run commit-msg.sh script
        entry: hooks/commit-msg.sh
        language: script
        stages: [commit]
        types: [python]
        pass_filenames: false
