# ** info: this file is a copy of https://github.com/joseesco24/postgres_users_db/blob/main/docker-compose.yml withut the build commands

version: "3.8"

services:
  postgres_users_db:
    container_name: postgres_users_db
    image: ghcr.io/joseesco24/postgres_users_db:latest
    networks:
      - dockerized_databases_network
    ports:
      - target: 5432
        published: 5434
        protocol: tcp
    volumes:
      - type: volume
        source: postgres_users_db_disc
        target: /var/lib/postgresql/data

networks:
  dockerized_databases_network:
    name: dockerized_databases_network
    external: false
    driver: bridge

volumes:
  postgres_users_db_disc:
