version: "3.8"

services:
  users_crud_api_python_app:
    container_name: users_crud_api_python_app
    image: ghcr.io/joseesco24/users_crud_api_python:latest
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - dockerized_database_network
    environment:
      DATABASE_USER: schema_1_user
      DATABASE_NAME: users_db
      DATABASE_PASSWORD: schema_1_user
      DATABASE_SCHEMA: schema_1
      DATABASE_HOST: dockerized_database
      DATABASE_PORT: 5432
      ENVIRONMENT_MODE: production
      SERVER_PORT: 10048
    ports:
      - target: 10048
        published: 10048
        protocol: tcp
    depends_on:
      - dockerized_database

  dockerized_database:
    container_name: dockerized_database
    image: ghcr.io/joseesco24/postgres_users_db:latest
    networks:
      - dockerized_database_network
    ports:
      - target: 5432
        published: 5434
        protocol: tcp
    volumes:
      - type: volume
        source: dockerized_database_disc
        target: /var/lib/postgresql/data

networks:
  dockerized_database_network:
    name: dockerized_database_network
    external: false
    driver: bridge

volumes:
  dockerized_database_disc:
