version: "3.8"

services:

  users_crud_api_python_app:
    container_name: users_crud_api_python_app
    image: ghcr.io/joseesco24/users_crud_api_python:latest
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - dockerized_database_network
    ports:
      - target: 3048
        published: 3048
        protocol: tcp
    depends_on:
      - dockerized_database

  dockerized_database:
    container_name: dockerized_database
    image: ghcr.io/joseesco24/postgres_users_db:latest
    networks:
      - dockerized_database_network
    ports:
      - target: 5432
        published: 5434
        protocol: tcp
    volumes:
      - type: volume
        source: dockerized_database_disc
        target: /var/lib/postgresql/data

networks:

  dockerized_database_network:
    name: dockerized_database_network
    external: false
    driver: bridge

volumes:

  dockerized_database_disc:
