type users {
  internal_id: String
  estatal_id: Integer
  first_name: String
  last_name: String
  phone_number: Integer
  email: String
  gender: String
  birthday: String
  creation: String
  modification: String
}
